spring:
  datasource:
    continue-on-error: false
    sql-script-encoding: UTF-8
    initialization-mode: @db.init-mode@ # embedded|always|never
    url: ~
    username: @db.username@
    password: @db.password@
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa:
    properties:
      hibernate:
        show_sql: false # true for log to console directly
        dialect: org.hibernate.dialect.HSQLDialect
    hibernate:
      ddl-auto: @jpa.ddl-auto@ # none | create | create-drop | update | validate
      #naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl #ImplicitNamingStrategyComponentPathImpl
