spring:
  datasource:
    url: @db.url@
    username: @db.username@
    password: @db.password@
    schema: # available when initialization-mode=always
    continue-on-error: false
    sql-script-encoding: UTF-8
    initialization-mode: @db.init-mode@ # embedded|always|never
      # drop
      - classpath:tech/simter/ymd/sql/@db.platform@/schema-drop.sql
      # create
      - classpath:tech/simter/ymd/sql/@db.platform@/schema-create.sql
    data: # available when initialization-mode=always
      - classpath:tech/simter/ymd/sql/@db.platform@/data.sql
