module:
  version:
    simter-ymd: @project.version@
  rest-context-path:
    simter-ymd: /ymd
server:
  port: ${port:8084}
  servlet:
    context-path: /
  server-header: @project.artifactId@-@project.version@
spring:
  main:
    banner-mode: 'off'
  profiles:
    active:
      - @app.env@
      - @app.dao@
  application:
    name: @project.artifactId@-@project.version@
  jackson:
    default-property-inclusion: NON_EMPTY # see enum of com.fasterxml.jackson.annotation.JsonInclude.Include
