spring:
  datasource:
    continue-on-error: false
    sql-script-encoding: UTF-8
    initialization-mode: @db.init-mode@ # embedded|always|never
    url: jdbc:postgresql://@db.host@:@db.port@/@db.name@
    username: @db.username@
    password: @db.password@
    driver-class-name: org.postgresql.Driver
    schema: # available when initialization-mode=always
      # drop
      - classpath:tech/simter/ymd/sql/@db.platform@/schema-drop.sql
      # create
      - classpath:tech/simter/ymd/sql/@db.platform@/schema-create.sql
    data: # available when initialization-mode=always
      - classpath:tech/simter/ymd/sql/@db.platform@/data.sql
  jpa:
    properties:
      hibernate:
        show_sql: false # true for log to console directly
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: @jpa.ddl-auto@ # none | create | create-drop | update | validate
      #naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl #ImplicitNamingStrategyComponentPathImpl
